/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fees_management_system;
import java.awt.Color;

import java.awt.Color;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JFrame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Akash
 */
public class PrintReceipt extends javax.swing.JFrame {

    /**
     * Creates new form PrintReceipt
     */
    public PrintReceipt() {
        initComponents();
        getRecords();
        Container c=getContentPane();
        c.setBackground(new Color(0,153,153));
    }
    
    public void getRecords()
    {
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/fees_management","root","akash123");
            PreparedStatement pst=con.prepareStatement("select * from fees_details order by receipt_no desc limit 1");
            ResultSet rs = pst.executeQuery();
            rs.next();            
            txt_receiptno.setText(rs.getString("receipt_no"));
            txt_paymentMode.setText(rs.getString("payment_mode"));
            String paymentMode = rs.getString("payment_mode");
            
            if(paymentMode.equalsIgnoreCase("cash"))
            {
                lbl_cheque_dd.setText("Cheque No ");
                txt_cheque_dd.setText("-");
                txt_bankName.setText("-");
            }
            if(paymentMode.equalsIgnoreCase("cheque"))
            {
                lbl_cheque_dd.setText("Cheque No ");
                txt_cheque_dd.setText(rs.getString("cheque_no"));
                txt_bankName.setText(rs.getString("bank_name"));
            }
            if(paymentMode.equalsIgnoreCase("dd"))
            {
                lbl_cheque_dd.setText("DD No ");
                txt_cheque_dd.setText(rs.getString("dd_No"));
                txt_bankName.setText(rs.getString("bank_name"));
            }
            if(paymentMode.equalsIgnoreCase("card"))
            {
                lbl_cheque_dd.setText("Cheque No ");
                txt_cheque_dd.setText(rs.getString("-"));
                txt_bankName.setText(rs.getString("bank_name"));
            }
            txt_receivedFrom.setText(rs.getString("student_name"));
            txt_date.setText(rs.getString("date"));
            txt_gstin.setText(rs.getString("gst_in"));
            txt_year1.setText(rs.getString("year1"));
            txt_year2.setText(rs.getString("year2"));
            
            txt_initialAmount.setText(rs.getString("amount"));
            txt_cgst.setText(rs.getString("c_gst"));
            txt_sgst.setText(rs.getString("s_gst"));
            txt_total.setText(rs.getString("total_amount"));
            txt_totalInWords.setText(rs.getString("total_in_words"));
            txt_courseName.setText(rs.getString("course_name"));
            
            
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSideBar = new javax.swing.JPanel();
        panelClist = new javax.swing.JPanel();
        btnClist = new javax.swing.JLabel();
        panelHome4 = new javax.swing.JPanel();
        btnHome4 = new javax.swing.JLabel();
        panelHome5 = new javax.swing.JPanel();
        btnHome5 = new javax.swing.JLabel();
        panelHome6 = new javax.swing.JPanel();
        btnHome6 = new javax.swing.JLabel();
        panelHome = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        panelSrecord = new javax.swing.JPanel();
        btnSrecord = new javax.swing.JLabel();
        panelLogout = new javax.swing.JPanel();
        btnLogout = new javax.swing.JLabel();
        panelEcourse = new javax.swing.JPanel();
        btnEcourse = new javax.swing.JLabel();
        panelVallrecord = new javax.swing.JPanel();
        btnVallrecord = new javax.swing.JLabel();
        panelBack = new javax.swing.JPanel();
        btnBack = new javax.swing.JLabel();
        panelprint = new javax.swing.JPanel();
        btn_print = new javax.swing.JLabel();
        paneledit = new javax.swing.JPanel();
        btn_edit = new javax.swing.JLabel();
        panel_print = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_receiptno = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_paymentMode = new javax.swing.JLabel();
        lbl_cheque_dd = new javax.swing.JLabel();
        txt_cheque_dd = new javax.swing.JLabel();
        lbl_bankName = new javax.swing.JLabel();
        txt_bankName = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        txt_receivedFrom1 = new javax.swing.JLabel();
        txt_year1 = new javax.swing.JLabel();
        txt_year2 = new javax.swing.JLabel();
        txt_receivedFrom4 = new javax.swing.JLabel();
        txt_receivedFrom = new javax.swing.JLabel();
        txt_date = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_gstin = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txt_courseName = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_sgst = new javax.swing.JLabel();
        txt_cgst = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_initialAmount = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_total = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_totalInWords = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSideBar.setBackground(new java.awt.Color(0, 102, 102));
        panelSideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelClist.setBackground(new java.awt.Color(0, 102, 102));
        panelClist.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelClist.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClist.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnClist.setForeground(new java.awt.Color(255, 255, 255));
        btnClist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/list_1.png"))); // NOI18N
        btnClist.setText(" Course List");
        btnClist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClistMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClistMouseExited(evt);
            }
        });
        panelClist.add(btnClist, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 300, 70));

        panelHome4.setBackground(new java.awt.Color(0, 102, 102));
        panelHome4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelHome4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome4.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnHome4.setForeground(new java.awt.Color(255, 255, 255));
        btnHome4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/home.png"))); // NOI18N
        btnHome4.setText("  HOME");
        btnHome4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHome4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHome4MouseExited(evt);
            }
        });
        panelHome4.add(btnHome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 260, 70));

        panelClist.add(panelHome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 330, 70));

        panelHome5.setBackground(new java.awt.Color(0, 102, 102));
        panelHome5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelHome5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome5.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnHome5.setForeground(new java.awt.Color(255, 255, 255));
        btnHome5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/home.png"))); // NOI18N
        btnHome5.setText("  HOME");
        btnHome5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHome5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHome5MouseExited(evt);
            }
        });
        panelHome5.add(btnHome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 260, 70));

        panelHome6.setBackground(new java.awt.Color(0, 102, 102));
        panelHome6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelHome6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome6.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnHome6.setForeground(new java.awt.Color(255, 255, 255));
        btnHome6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/home.png"))); // NOI18N
        btnHome6.setText("  HOME");
        btnHome6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHome6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHome6MouseExited(evt);
            }
        });
        panelHome6.add(btnHome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 260, 70));

        panelHome5.add(panelHome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 330, 70));

        panelClist.add(panelHome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 330, 70));

        panelSideBar.add(panelClist, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 330, 70));

        panelHome.setBackground(new java.awt.Color(0, 102, 102));
        panelHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/home.png"))); // NOI18N
        btnHome.setText("  HOME");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        panelHome.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 300, 70));

        panelSideBar.add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 330, 70));

        panelSrecord.setBackground(new java.awt.Color(0, 102, 102));
        panelSrecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelSrecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSrecord.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnSrecord.setForeground(new java.awt.Color(255, 255, 255));
        btnSrecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/search2.png"))); // NOI18N
        btnSrecord.setText(" Search Record");
        btnSrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSrecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSrecordMouseExited(evt);
            }
        });
        panelSrecord.add(btnSrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 300, 70));

        panelSideBar.add(panelSrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 330, 70));

        panelLogout.setBackground(new java.awt.Color(0, 102, 102));
        panelLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/logout.png"))); // NOI18N
        btnLogout.setText(" Logout");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        panelLogout.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 280, 70));

        panelSideBar.add(panelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 330, 70));

        panelEcourse.setBackground(new java.awt.Color(0, 102, 102));
        panelEcourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelEcourse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEcourse.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnEcourse.setForeground(new java.awt.Color(255, 255, 255));
        btnEcourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit2.png"))); // NOI18N
        btnEcourse.setText(" Edit Courses");
        btnEcourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEcourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEcourseMouseExited(evt);
            }
        });
        panelEcourse.add(btnEcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 300, 70));

        panelSideBar.add(panelEcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 330, 70));

        panelVallrecord.setBackground(new java.awt.Color(0, 102, 102));
        panelVallrecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelVallrecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVallrecord.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnVallrecord.setForeground(new java.awt.Color(255, 255, 255));
        btnVallrecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/view all record.png"))); // NOI18N
        btnVallrecord.setText(" View All Record");
        btnVallrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVallrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVallrecordMouseExited(evt);
            }
        });
        panelVallrecord.add(btnVallrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 300, 70));

        panelSideBar.add(panelVallrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 330, 70));

        panelBack.setBackground(new java.awt.Color(0, 102, 102));
        panelBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/left-arrow.png"))); // NOI18N
        btnBack.setText(" Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        panelBack.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 290, 70));

        panelSideBar.add(panelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 330, 70));

        panelprint.setBackground(new java.awt.Color(0, 102, 102));
        panelprint.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelprint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_print.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btn_print.setForeground(new java.awt.Color(255, 255, 255));
        btn_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/printer-.png"))); // NOI18N
        btn_print.setText(" Print");
        btn_print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_printMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_printMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_printMouseExited(evt);
            }
        });
        panelprint.add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 280, 70));

        panelSideBar.add(panelprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, 330, 70));

        paneledit.setBackground(new java.awt.Color(0, 102, 102));
        paneledit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        paneledit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_edit.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit2.png"))); // NOI18N
        btn_edit.setText(" edit");
        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editMouseExited(evt);
            }
        });
        paneledit.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 280, 70));

        panelSideBar.add(paneledit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 660, 330, 70));

        getContentPane().add(panelSideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 1040));

        panel_print.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("University Institute of Engineering and Technology");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 102));
        jLabel3.setText("Payment Mode :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("School of Engineering and Technology");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/download.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1220, 6));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1220, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Jhansi , Uttar Pradesh");

        txt_receiptno.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        txt_receiptno.setForeground(new java.awt.Color(51, 0, 102));
        txt_receiptno.setText("receipt no : ");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 102));
        jLabel7.setText("Head");

        txt_paymentMode.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        txt_paymentMode.setForeground(new java.awt.Color(51, 0, 102));
        txt_paymentMode.setText("Payment Mode :");

        lbl_cheque_dd.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        lbl_cheque_dd.setForeground(new java.awt.Color(51, 0, 102));
        lbl_cheque_dd.setText("Cheque_dd :");

        txt_cheque_dd.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        txt_cheque_dd.setForeground(new java.awt.Color(51, 0, 102));
        txt_cheque_dd.setText("Cheque_dd :");

        lbl_bankName.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        lbl_bankName.setForeground(new java.awt.Color(51, 0, 102));
        lbl_bankName.setText("Bank Name :");

        txt_bankName.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        txt_bankName.setForeground(new java.awt.Color(51, 0, 102));
        txt_bankName.setText("Bank Name :");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 102));
        jLabel10.setText("GSTIN :");

        lbl.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        lbl.setForeground(new java.awt.Color(51, 0, 102));
        lbl.setText("The following payment in the college office the year ");

        txt_receivedFrom1.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        txt_receivedFrom1.setForeground(new java.awt.Color(51, 0, 102));
        txt_receivedFrom1.setText("Received From :");

        txt_year1.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        txt_year1.setForeground(new java.awt.Color(51, 0, 102));
        txt_year1.setText("2021");

        txt_year2.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        txt_year2.setForeground(new java.awt.Color(51, 0, 102));
        txt_year2.setText("2021");

        txt_receivedFrom4.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        txt_receivedFrom4.setForeground(new java.awt.Color(51, 0, 102));
        txt_receivedFrom4.setText("-");

        txt_receivedFrom.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        txt_receivedFrom.setForeground(new java.awt.Color(51, 0, 102));
        txt_receivedFrom.setText("Received From :");

        txt_date.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        txt_date.setForeground(new java.awt.Color(51, 0, 102));
        txt_date.setText("Date :");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 0, 102));
        jLabel12.setText("Date :");

        txt_gstin.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        txt_gstin.setForeground(new java.awt.Color(51, 0, 102));
        txt_gstin.setText("GSTIN :");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 153));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 153));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 153));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 153));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 102));
        jLabel13.setText("receipt no :         SET-");

        txt_courseName.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        txt_courseName.setForeground(new java.awt.Color(51, 0, 102));
        txt_courseName.setText("1");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 0, 102));
        jLabel15.setText("Amount(rs)");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 0, 102));
        jLabel16.setText("Sr No");

        txt_sgst.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        txt_sgst.setForeground(new java.awt.Color(51, 0, 102));
        txt_sgst.setText("sgst");

        txt_cgst.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        txt_cgst.setForeground(new java.awt.Color(51, 0, 102));
        txt_cgst.setText("cgst");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 0, 102));
        jLabel18.setText("1");

        txt_initialAmount.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        txt_initialAmount.setForeground(new java.awt.Color(51, 0, 102));
        txt_initialAmount.setText("cgst");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 0, 102));
        jLabel20.setText("cgst(9%)");

        txt_total.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        txt_total.setForeground(new java.awt.Color(51, 0, 102));
        txt_total.setText("total");

        jSeparator3.setBackground(new java.awt.Color(0, 0, 153));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 153));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 0, 102));
        jLabel22.setText("Receiver Signature");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 0, 102));
        jLabel23.setText("sgst(9%)");

        txt_totalInWords.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        txt_totalInWords.setForeground(new java.awt.Color(51, 0, 102));
        txt_totalInWords.setText("total in words :");

        jSeparator4.setBackground(new java.awt.Color(0, 0, 153));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 153));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 0, 102));
        jLabel24.setText("total in words :");

        javax.swing.GroupLayout panel_printLayout = new javax.swing.GroupLayout(panel_print);
        panel_print.setLayout(panel_printLayout);
        panel_printLayout.setHorizontalGroup(
            panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_printLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_printLayout.createSequentialGroup()
                        .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_bankName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_cheque_dd, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_receivedFrom1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_printLayout.createSequentialGroup()
                                .addComponent(txt_cheque_dd, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_receivedFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel_printLayout.createSequentialGroup()
                        .addComponent(lbl)
                        .addGap(18, 18, 18)
                        .addComponent(txt_year1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_receivedFrom4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_year2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(257, 257, 257))
            .addGroup(panel_printLayout.createSequentialGroup()
                .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_printLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_printLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_printLayout.createSequentialGroup()
                        .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_paymentMode)
                            .addComponent(txt_receiptno))
                        .addGap(211, 211, 211)
                        .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_gstin)
                            .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txt_bankName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panel_printLayout.createSequentialGroup()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_printLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_printLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 965, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_printLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_printLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
            .addGroup(panel_printLayout.createSequentialGroup()
                .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_printLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(229, 229, 229)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201)
                        .addComponent(jLabel15))
                    .addGroup(panel_printLayout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_courseName, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(180, 180, 180)
                        .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_initialAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cgst, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_sgst, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_printLayout.createSequentialGroup()
                        .addGap(549, 549, 549)
                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_printLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_totalInWords, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_printLayout.createSequentialGroup()
                        .addGap(524, 524, 524)
                        .addComponent(jLabel22)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_printLayout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1164, Short.MAX_VALUE)))
            .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_printLayout.createSequentialGroup()
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 1244, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_printLayout.createSequentialGroup()
                    .addGap(497, 497, 497)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(589, Short.MAX_VALUE)))
        );
        panel_printLayout.setVerticalGroup(
            panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_printLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_printLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_receiptno)
                    .addComponent(jLabel12)
                    .addComponent(txt_date)
                    .addComponent(jLabel13))
                .addGap(17, 17, 17)
                .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_paymentMode)
                    .addComponent(jLabel10)
                    .addComponent(txt_gstin))
                .addGap(18, 18, 18)
                .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_cheque_dd)
                    .addComponent(txt_cheque_dd))
                .addGap(18, 18, 18)
                .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_receivedFrom)
                    .addComponent(txt_receivedFrom1))
                .addGap(18, 18, 18)
                .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_bankName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bankName))
                .addGap(18, 18, 18)
                .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl)
                    .addComponent(txt_year1)
                    .addComponent(txt_receivedFrom4)
                    .addComponent(txt_year2))
                .addGap(21, 21, 21)
                .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_courseName)
                    .addComponent(txt_initialAmount))
                .addGap(18, 18, 18)
                .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cgst)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_sgst)
                    .addComponent(jLabel23))
                .addGap(27, 27, 27)
                .addComponent(txt_total)
                .addGap(18, 18, 18)
                .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_totalInWords, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addGap(0, 153, Short.MAX_VALUE))
            .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_printLayout.createSequentialGroup()
                    .addContainerGap(493, Short.MAX_VALUE)
                    .addComponent(jLabel18)
                    .addGap(346, 346, 346)))
            .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_printLayout.createSequentialGroup()
                    .addContainerGap(423, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(434, 434, 434)))
            .addGroup(panel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_printLayout.createSequentialGroup()
                    .addContainerGap(604, Short.MAX_VALUE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(253, 253, 253)))
        );

        getContentPane().add(panel_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 1250, 860));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Print Receipt");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 300, 50));

        setSize(new java.awt.Dimension(1977, 1099));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClistMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClistMouseEntered
        Color clr=new Color(0,153,153);
        panelClist.setBackground(clr);
    }//GEN-LAST:event_btnClistMouseEntered

    private void btnClistMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClistMouseExited
        Color clr=new Color(0,103,103);
        panelClist.setBackground(clr);
    }//GEN-LAST:event_btnClistMouseExited

    private void btnHome4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome4MouseEntered

    private void btnHome4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome4MouseExited

    private void btnHome5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome5MouseEntered

    private void btnHome5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome5MouseExited

    private void btnHome6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome6MouseEntered

    private void btnHome6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome6MouseExited

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        Color clr=new Color(0,153,153);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        Color clr=new Color(0,103,103);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnSrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSrecordMouseEntered
        Color clr=new Color(0,153,153);
        panelSrecord.setBackground(clr);
    }//GEN-LAST:event_btnSrecordMouseEntered

    private void btnSrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSrecordMouseExited
        Color clr=new Color(0,103,103);
        panelSrecord.setBackground(clr);
    }//GEN-LAST:event_btnSrecordMouseExited

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        Color clr=new Color(0,153,153);
        panelLogout.setBackground(clr);
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        Color clr=new Color(0,103,103);
        panelLogout.setBackground(clr);
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnEcourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEcourseMouseEntered
        Color clr=new Color(0,153,153);
        panelEcourse.setBackground(clr);
    }//GEN-LAST:event_btnEcourseMouseEntered

    private void btnEcourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEcourseMouseExited
        Color clr=new Color(0,103,103);
        panelEcourse.setBackground(clr);
    }//GEN-LAST:event_btnEcourseMouseExited

    private void btnVallrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVallrecordMouseEntered
        Color clr=new Color(0,153,153);
        panelVallrecord.setBackground(clr);
    }//GEN-LAST:event_btnVallrecordMouseEntered

    private void btnVallrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVallrecordMouseExited
        Color clr=new Color(0,103,103);
        panelVallrecord.setBackground(clr);
    }//GEN-LAST:event_btnVallrecordMouseExited

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        Color clr=new Color(0,153,153);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        Color clr=new Color(0,103,103);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_btnBackMouseExited

    private void btn_printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseEntered
        Color clr=new Color(0,153,153);
        panelprint.setBackground(clr);
    }//GEN-LAST:event_btn_printMouseEntered

    private void btn_printMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseExited
        Color clr=new Color(0,103,103);
        panelprint.setBackground(clr);
    }//GEN-LAST:event_btn_printMouseExited

    private void btn_editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseEntered
        Color clr=new Color(0,153,153);
        paneledit.setBackground(clr);
    }//GEN-LAST:event_btn_editMouseEntered

    private void btn_editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseExited
        Color clr=new Color(0,103,103);
        paneledit.setBackground(clr);
    }//GEN-LAST:event_btn_editMouseExited

    private void btn_printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseClicked
   PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
                panel_print.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }
    }//GEN-LAST:event_btn_printMouseClicked

    private void btn_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseClicked
        UpdateFeesDetails update = new UpdateFeesDetails();
        update.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_editMouseClicked

    private void btnSrecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSrecordMouseClicked
        searchRecord search=new searchRecord();
        search.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSrecordMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
       Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
           Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnClist;
    private javax.swing.JLabel btnEcourse;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnHome4;
    private javax.swing.JLabel btnHome5;
    private javax.swing.JLabel btnHome6;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnSrecord;
    private javax.swing.JLabel btnVallrecord;
    private javax.swing.JLabel btn_edit;
    private javax.swing.JLabel btn_print;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl_bankName;
    private javax.swing.JLabel lbl_cheque_dd;
    private javax.swing.JPanel panelBack;
    private javax.swing.JPanel panelClist;
    private javax.swing.JPanel panelEcourse;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelHome4;
    private javax.swing.JPanel panelHome5;
    private javax.swing.JPanel panelHome6;
    private javax.swing.JPanel panelLogout;
    private javax.swing.JPanel panelSideBar;
    private javax.swing.JPanel panelSrecord;
    private javax.swing.JPanel panelVallrecord;
    private javax.swing.JPanel panel_print;
    private javax.swing.JPanel paneledit;
    private javax.swing.JPanel panelprint;
    private javax.swing.JLabel txt_bankName;
    private javax.swing.JLabel txt_cgst;
    private javax.swing.JLabel txt_cheque_dd;
    private javax.swing.JLabel txt_courseName;
    private javax.swing.JLabel txt_date;
    private javax.swing.JLabel txt_gstin;
    private javax.swing.JLabel txt_initialAmount;
    private javax.swing.JLabel txt_paymentMode;
    private javax.swing.JLabel txt_receiptno;
    private javax.swing.JLabel txt_receivedFrom;
    private javax.swing.JLabel txt_receivedFrom1;
    private javax.swing.JLabel txt_receivedFrom4;
    private javax.swing.JLabel txt_sgst;
    private javax.swing.JLabel txt_total;
    private javax.swing.JLabel txt_totalInWords;
    private javax.swing.JLabel txt_year1;
    private javax.swing.JLabel txt_year2;
    // End of variables declaration//GEN-END:variables
}
